# Generated by Django 3.2.5 on 2021-11-07 12:48

import dap.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=None, max_length=255)),
                ('product_price', models.FloatField(default=True)),
                ('is_discount_price', models.BooleanField(default=False)),
                ('product_discount_price', models.FloatField(default=True)),
                ('product_description', models.TextField(help_text='Input some information', max_length=255, verbose_name='Product Detail')),
                ('product_front_image', models.FileField(default=False, max_length=300, upload_to=dap.models.UploadProduct.get_product_uploaded_front_image_filepath)),
                ('product_back_image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=dap.models.UploadProduct.get_product_uploaded_back_image_filepath)),
                ('product_status', models.BooleanField(default=False)),
                ('product_is_digital', models.BooleanField(blank=True, default=False, null=True)),
                ('product_meta_title', models.CharField(blank=True, default=False, max_length=125, null=True)),
                ('product_meta_description', models.TextField(default=False, help_text='Input some information', max_length=255, verbose_name='Product Detail')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product_categories', models.CharField(choices=[('technology', 'Technology'), ('fashion', 'Fashion'), ('accessory', 'Accessory')], default=True, max_length=150)),
                ('product_size', models.CharField(choices=[('small', 'Small'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=25)),
                ('product_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='red', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=45)),
                ('auth_token', models.CharField(default=False, max_length=100)),
                ('password', models.CharField(default=False, max_length=45)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dap.userregistration')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dap.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dap.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dap.uploadproduct')),
            ],
        ),
    ]
