# Generated by Django 3.2.5 on 2021-11-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='name',
        ),
    ]
