# Generated by Django 3.2.5 on 2021-11-05 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(default=None, max_length=125)),
                ('product_sku', models.CharField(default=None, max_length=30)),
                ('product_categories', models.CharField(choices=[('technology', 'Technology'), ('fashion', 'Fashion'), ('accessory', 'Accessory')], default=True, max_length=150)),
                ('product_price', models.FloatField(default=True)),
                ('product_summary', models.TextField(help_text='Input some information', max_length=255, verbose_name='Product Detail')),
                ('product_status', models.BooleanField(default=False)),
                ('product_description', models.TextField(default=False, help_text='Input some information', max_length=255, verbose_name='Product Detail')),
                ('product_meta_title', models.CharField(default=None, max_length=125)),
                ('product_meta_description', models.TextField(default=False, help_text='Input some information', max_length=255, verbose_name='Product Detail')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('auth_token', models.CharField(default=False, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg_User',
        ),
    ]
