# Generated by Django 3.2.5 on 2021-10-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
    ]
