# Generated by Django 3.2.5 on 2021-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0002_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(default=None, max_length=125)),
                ('product_sku', models.CharField(default=None, max_length=30)),
                ('product_categories', models.CharField(choices=[('technology', 'Technology'), ('fashion', 'Fashion'), ('accessory', 'Accessory')], default=True, max_length=150)),
                ('product_price', models.FloatField(default=True)),
                ('product_summary', models.TextField(help_text='Input some information', max_length=255, verbose_name='Product Detail')),
                ('product_status', models.BooleanField(default=False)),
            ],
        ),
    ]
