# Generated by Django 3.2.5 on 2021-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0002_auto_20211105_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='password1',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='password2',
            field=models.CharField(default=False, max_length=45),
        ),
    ]
