# Generated by Django 3.2.5 on 2021-11-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0003_auto_20211105_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='password1',
            new_name='c_password',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='password2',
            new_name='password',
        ),
    ]
