# Generated by Django 3.2.5 on 2021-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0003_add_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='product_description',
            field=models.TextField(default=False, help_text='Input some information', max_length=255, verbose_name='Product Detail'),
        ),
        migrations.AddField(
            model_name='add_products',
            name='product_meta_description',
            field=models.TextField(default=False, help_text='Input some information', max_length=255, verbose_name='Product Detail'),
        ),
        migrations.AddField(
            model_name='add_products',
            name='product_meta_title',
            field=models.CharField(default=None, max_length=125),
        ),
    ]
