# Generated by Django 3.2.5 on 2021-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0004_auto_20211105_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='c_password',
            new_name='c_assword',
        ),
    ]
