# Generated by Django 3.2.5 on 2021-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0005_rename_c_password_userregistration_c_assword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='c_assword',
            new_name='c_password',
        ),
    ]
