# Generated by Django 3.2.5 on 2021-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0006_rename_c_assword_userregistration_c_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='c_password',
            new_name='c_passwod',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='password',
            new_name='passwor',
        ),
    ]
