# Generated by Django 3.2.5 on 2021-11-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap', '0007_auto_20211105_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='c_passwod',
            new_name='c_password',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='passwor',
            new_name='password',
        ),
    ]
